export const adaptCollection = collection => {
  return {
    id: collection._id,
    title: collection.title,
    description: collection.desc || '',
    desc: collection.desc || '',
    goal: collection.target || 0,
    target: collection.target || 0,
    raised: collection.collected || 0,
    collected: collection.collected || 0,
    status: collection.status,
    createdAt: collection.createdAt,
    updatedAt: collection.updatedAt || collection.createdAt,
    peopleDonate: collection.peopleDonate || 0,
    importance: collection.importance || 'normal',
    image: collection.image || [],
    long_desc: collection.long_desc || {},
    alt: collection.alt || collection.title || 'Collection image',
    value: collection.value,
    days: collection.days,
    period: collection.period,
    quantity: collection.quantity,
    currency: collection.currency,
    language: collection.language,
    type: collection.type,
    closedAt: collection.closedAt,
    translations: collection.translations,
  };
};
